x-common-volumes: &common-volumes
  - ./:/MoneyPrinterTurbo:rw
  - ./storage:/MoneyPrinterTurbo/storage:rw

services:
  webui:
    build:
      context: ..
      dockerfile: app/Dockerfile
    image: moneyprinterturbo-webui:latest
    container_name: moneyprinterturbo-webui-new
    ports:
      - "8501:8501"
    command: [ "streamlit", "run", "./webui/Main.py", "--browser.serverAddress=0.0.0.0", "--server.enableCORS=True", "--browser.gatherUsageStats=False", "pip install --no-cache-dir -r requirements.txt websockets" ]
    volumes:
      - ../:/MoneyPrinterTurbo:rw
      - ../storage:/MoneyPrinterTurbo/storage:rw
    restart: unless-stopped
    environment:
      - PYTHONPATH=/MoneyPrinterTurbo
      - HOST=0.0.0.0
      - PORT=8501
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=none
      - DATABASE_URL=postgres://postgres:postgres@db:5432/app
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
  api:
    build:
      context: ..
      dockerfile: app/Dockerfile
    image: moneyprinterturbo-api:latest
    container_name: moneyprinterturbo-api-new
    ports:
      - "8080:8080"
    command: [
      "python3", "-m", "uvicorn", "app.main:app",
      "--host", "0.0.0.0",
      "--port", "8080",
      "--workers", "4",
      "--access-log",
      "--log-level", "info"
    ]
    volumes:
      - ../:/MoneyPrinterTurbo:rw
      - ../storage:/MoneyPrinterTurbo/storage:rw
    restart: unless-stopped
    environment:
      - PYTHONPATH=/MoneyPrinterTurbo
      - HOST=0.0.0.0
      - PORT=8080
      - ENVIRONMENT=production
      - ALLOWED_ORIGINS=http://localhost:8501,http://localhost:3000
      - TRUSTED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DATABASE_URL=postgres://postgres:postgres@db:5432/app
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  redis:
    image: redis:7-alpine
    container_name: moneyprinterturbo-redis-new
    restart: unless-stopped
    # Expose Redis port internally only to avoid host port conflicts
    expose:
      - "6379"
    command: [
      "redis-server",
      "--maxmemory", "512mb",
      "--maxmemory-policy", "allkeys-lru",
      "--appendonly", "yes",
      "--save", "60", "1000",
      "--tcp-keepalive", "60",
      "--timeout", "0",
      "--tcp-backlog", "511"
    ]
    volumes:
      - redis_data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mcp-server:
    build:
      context: ..
      dockerfile: app/Dockerfile
    image: moneyprinterturbo-mcp:latest
    container_name: moneyprinterturbo-mcp-new
    ports:
      - "8081:8081"
    command: [
      "/MoneyPrinterTurbo/scripts/start_mcp_server.sh"
    ]
    volumes:
      - ../:/MoneyPrinterTurbo:rw
      - ../storage:/MoneyPrinterTurbo/storage:rw
    restart: unless-stopped
    environment:
      - PYTHONPATH=/MoneyPrinterTurbo
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8081
      - ENVIRONMENT=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ENABLE_REDIS=true
      - PYTHONUNBUFFERED=1
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python3", "-c", "import asyncio; import websockets; import sys; sys.exit(0 if asyncio.run(websockets.connect('ws://localhost:8081').close()) is None else 1)"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15-alpine
    container_name: moneyprinterturbo-postgres-new
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mpt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
